language: node_js

services:
  - docker

node_js:
  - '10'

sudo: false

os:
  - linux

dist: xenial

install:
  - npm ci

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish
  on:
    branch: master
    repo: anacierdem/ed64
