name: Github Release

on:
  push

jobs:
  Release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm ci

      - name: Package
        run: |
          npm run pack
          mv ed64.exe loader64.exe

      - name: Release executable
        uses: softprops/action-gh-release@v1
        with:
          files: loader64.exe